export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO';
export const CERRAR_SESSION = 'CERRAR_SESSION';

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO'
export const REGISTRO_ERROR = 'REGISTRO_ERROR'

export const LIMPIAR_ALERTA = 'LIMPIAR_ALERTA'
export const MISTRAR_ALERTA = 'MOSTRAR_ALERTA'

export const LOGIN_EXITOSO = 'LOGIN_EXITOSO'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const SUBIR_ARCHIVO = 'SUBIR_ARCHIVO';
export const SUBIR_ARCHIVO_EXITO = 'SUBIR_ARCHIVO_EXITO';
export const SUBIR_ARCHIVO_ERROR = 'SUBIR_ARCHIVO_ERROR';

export const CREAR_ENLACE_EXITO = 'CREAR_ENLACE_EXITO';
export const CREAR_ENLACE_ERROR = 'CREAR_ENLACE_ERROR';

export const LIMPIAR_STATE = 'LIMPIAR_STATE';
export const AGREGAR_PASSWORD = 'AGREGAR_PASSWORD';
export const AGREGAR_DESCARGAS = 'AGREGAR_DESCARGAS';